
# File: _config.yml
webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value

# basic options 
title: Zekarias M.
description: the web under construction! 
author: Zekarias M.
email: zekariasmulu@gmail.com
github_username:  ZekariasM
gem "github-pages", group: :jekyll_plugins

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
url: https://zekariasm.io
source:      _source
destination: _deploy
#show_downloads: "true" 
#google_analytics: [Your Google Analytics tracking ID]
